### ISSUE TITLE
LAB 5 - Spring profile production does not work

### ISSUE THREAD

**Issue by hodrigohamalho** [hodrigohamalho/fuse-workshop-doc#15]
application.properties still being used instead of application-prod.properties

**Comment by hodrigohamalho** [comment]
Fixed by somme @edeandrea commit.

**Comment by edeandrea** [comment]
Yeah some context here - passing `-Dspring.profiles.active=prod` to the `mvn fabric8:deploy` doesn't activate the profile when it triggers the S2I build. You need to make sure the `deployment.yml` has it as an environment variable. Either that or use the `spring-cloud-kubernetes` library and introduce a config map that the application reads.
