### ISSUE TITLE
Different Editor Version 

### ISSUE THREAD

**Issue by GuilhermeCamposo** [hodrigohamalho/fuse-workshop-doc#34]
The editor version displayed in the docs and what is deployed now is different. This makes the steps to reproduce the lab different. I believe this is happening because workspace configuration is point to the latest version of the editor, so over time we will have different versions. By the way, the editor displayed in the docs seems to be more easy to use. Do you know the version you used when you did the documentation?

**Comment by hodrigohamalho** [comment]
I already updated it.
thanks Guilherme
