### ISSUE TITLE
Eclipse Che

### ISSUE THREAD

**Issue by gmarotti** [hodrigohamalho/fuse-workshop-doc#6]
URL:
https://tutorial-web-app-webapp.apps.latam-c70e.openshiftworkshop.com/tutorial/fuse-workshop-doc.git-walkthroughs-00-project-setup/task/0

- A ordem da instrução não condiz com a imagem
- Trocar a imagem do "Eclipse che" para "Code Ready"

**Comment by hodrigohamalho** [comment]
Thanks @gmarotti !
