### ISSUE TITLE
CodeReady "Create Run command"

### ISSUE THREAD

**Issue by gmarotti** [hodrigohamalho/fuse-workshop-doc#7]
URL:
https://tutorial-web-app-webapp.apps.latam-c70e.openshiftworkshop.com/tutorial/fuse-workshop-doc.git-walkthroughs-00-project-setup/task/1

- Corrigir o local onde está a opção de "Create Run comand"

New path:
- selecionar o projeto ex.: "fuse-workshop"
- ir em "manage commands"
- clicar no "+" do lado do  dropdown "RUN" e criar o comando

**Comment by hodrigohamalho** [comment]
done.
